# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8816e413d3907041297699cffa7039c05c187e11d9ef95e67e6a48593d408148ff188a4993fa44522645a1c5890a0d6f72897f9d4664dffb90c1c6f2b5641e53

test:
  secret_key_base: cf6e9f9e393cc21fa940d2752aea7bdf9066fd46aace287f5c149e6889a8705afe1f4618ada362c73fa6a609a8236dcb0b4218da439761c3f8ae3977d8a200f6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
